[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "amqtt>=0.11.3",
    "flask>=3.1.3",
]

[project.scripts]
case2-http-server = "http_server.app:main"
case2-mqtt-broker = "mqtt_broker.server:main"
