[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "amqtt>=0.11.3",
    "flask>=3.1.3",
    "websockets>=15.0.1",
]

[project.scripts]
espesp-http-client = "http_client.client:main"
espesp-http-server = "http_server.app:main"
espesp-mqtt-broker = "mqtt_broker.server:main"
espesp-mqtt-client = "mqtt_client.client:main"
espesp-ws-client = "ws_client.client:main"
espesp-ws-server = "ws_server.server:main"
